/**
 * An estimating measurer: widths from the tree and the text, no layout engine.
 * It reads the inline styles the engine itself wrote (widths, grids, padding,
 * the sidebar, font size and weight from the skin) and sizes text by summing
 * the advance widths Chromium reported for the default skin's fonts
 * (`glyphs.ts`, generated by `scripts/calibrate-glyphs.mjs`) — tabular
 * figures, uppercase letter-spaced labels and monospace code included.
 * Deterministic, and calibrated: `glyphs.test.ts` holds every string the
 * engine's own tests put on screen to within 3% of the browser.
 */
import { metrics } from '../metrics.js';
import { GLYPHS, MONO, type GlyphStyle } from './glyphs.js';
import type { Measurer } from '../engine/measure.js';

const px = (v: string | undefined) => (v && v.endsWith('px') ? parseFloat(v) : undefined);

/** The horizontal padding an element's inline style declares (the engine's only styling), px. */
export const horizontalPadding = (el: HTMLElement): number => {
  const l = px(el.style.paddingLeft), r = px(el.style.paddingRight);
  if (l !== undefined || r !== undefined) return (l ?? 0) + (r ?? 0);
  const parts = el.style.padding.split(/\s+/).map(px).filter((n): n is number => n !== undefined);
  if (parts.length === 0) return 0;
  return parts.length === 1 ? parts[0]! * 2 : parts.length === 2 ? parts[1]! * 2 : parts.length === 3 ? parts[1]! * 2 : parts[1]! + parts[3]!;
};

/** Elements whose width is their text: headings, cells, controls, inline runs. A `div` joins them when it is pinned to one line (`white-space: nowrap`): a Stat's value, the App's brand. */
export const TEXTUAL = new Set(['H1', 'H2', 'H3', 'TH', 'TD', 'BUTTON', 'SPAN', 'A', 'LABEL', 'OPTION', 'LEGEND']);

export interface TextStyle {
  /** Font size, px. Default the body size (14). */
  size?: number;
  /** Font weight. Default 400. */
  weight?: number;
  /** A monospace family (`text.code`): measured against the calibrated mono table. */
  mono?: boolean;
  /** `font-variant-numeric: tabular-nums`: every digit takes the tabular advance. */
  tabular?: boolean;
  /** `text-transform: uppercase`. */
  uppercase?: boolean;
  /** `letter-spacing`, em (added once per glyph). */
  spacing?: number;
}

/** The calibrated table nearest a style: same family first, then size, then the closest weight. */
export function tableFor(style: TextStyle = {}): GlyphStyle {
  const size = style.size ?? 14, weight = style.weight ?? 400, mono = !!style.mono;
  let best: GlyphStyle = 'body', score = Infinity;
  for (const key of Object.keys(GLYPHS) as GlyphStyle[]) {
    const t = GLYPHS[key];
    const s = ((t.family === MONO) !== mono ? 1e6 : 0) + Math.abs(t.size - size) * 100 + Math.abs(t.weight - weight);
    if (s < score) { score = s; best = key; }
  }
  return best;
}

const DIGIT = /[0-9]/;

/**
 * The width of a run of text, px: the sum of the calibrated advances of its
 * glyphs at the nearest table (a glyph the table does not know falls back to
 * `metrics.charWidth`, scaled to the size), plus `padding`. Under `tabular`
 * every digit takes the table's tabular advance; `uppercase` sums the upper
 * glyphs; `spacing` (em) is added per glyph, as `letter-spacing` is.
 */
export function textWidth(text: string, style: TextStyle = {}, padding = 0): number {
  const table = GLYPHS[tableFor(style)];
  const size = style.size ?? 14;
  const scale = size / table.size;
  const fallback = metrics.charWidth * (size / 14);
  const run = style.uppercase ? text.toUpperCase() : text;
  let sum = 0, n = 0;
  for (const g of run) {
    n++;
    const advance = style.tabular && DIGIT.test(g) ? table.tabularDigit : table.glyphs[g];
    sum += (advance ?? fallback / scale) * scale;
  }
  return sum + n * (style.spacing ?? 0) * size + padding;
}

const WEIGHT: Record<string, number> = { normal: 400, bold: 700, bolder: 700, lighter: 300 };
const em = (v: string | undefined): number | undefined => (v && v.endsWith('em') ? parseFloat(v) : undefined);

/**
 * The text style an element's inline styles (its own or an ancestor's) declare —
 * the skin writes `font-size`, `font-weight`, `font-family`, `text-transform`
 * and `letter-spacing`; blocks write `font-variant-numeric`. Each is read
 * from the nearest element that sets it, as inheritance would.
 */
export function textStyleOf(el: HTMLElement): TextStyle {
  const out: TextStyle = {};
  let size: number | undefined, weight: number | undefined, mono: boolean | undefined, tabular: boolean | undefined, uppercase: boolean | undefined, spacing: number | undefined;
  for (let n: HTMLElement | null = el; n; n = n.parentElement) {
    const s = n.style;
    if (size === undefined) size = px(s.fontSize);
    if (weight === undefined && s.fontWeight) weight = WEIGHT[s.fontWeight] ?? (Number(s.fontWeight) || undefined);
    if (mono === undefined && s.fontFamily) mono = /monospace|mono|menlo|consolas|courier/i.test(s.fontFamily);
    const fvn = s.getPropertyValue('font-variant-numeric');
    if (tabular === undefined && fvn) tabular = fvn.includes('tabular-nums');
    if (uppercase === undefined && s.textTransform) uppercase = s.textTransform === 'uppercase';
    if (spacing === undefined && s.letterSpacing) spacing = s.letterSpacing === 'normal' ? 0 : em(s.letterSpacing) ?? (px(s.letterSpacing) !== undefined && size ? px(s.letterSpacing)! / size : undefined);
  }
  if (size !== undefined) out.size = size;
  if (weight !== undefined) out.weight = weight;
  if (mono) out.mono = true;
  if (tabular) out.tabular = true;
  if (uppercase) out.uppercase = true;
  if (spacing) out.spacing = spacing;
  return out;
}

/** Whether an element is measured as text: text-shaped (or a one-line `div`) and not laid out as a box by the engine. */
export const isTextual = (el: HTMLElement): boolean =>
  (TEXTUAL.has(el.tagName) || (el.tagName === 'DIV' && el.style.whiteSpace === 'nowrap'))
  && el.style.display !== 'block' && el.style.display !== 'flex' && el.style.display !== 'grid';

/** Whether a child is laid out on its own line: a `div` (block by default) or anything the engine set `display: block|flex|grid`. */
const ownLine = (n: HTMLElement): boolean => n.tagName === 'DIV' || n.style.display === 'block' || n.style.display === 'flex' || n.style.display === 'grid';

/** An element's text on its own line: its text nodes and inline children, without children that sit on lines of their own (a table cell's folded values). */
export function ownText(el: HTMLElement): string {
  let out = '';
  for (const n of el.childNodes) {
    if (n.nodeType === 3) out += n.textContent ?? '';
    else if (n.nodeType === 1 && !ownLine(n as HTMLElement)) out += ownText(n as HTMLElement);
  }
  return out.replace(/\s+/g, ' ').trim();
}

/** The width of an element's own text, at its declared style, plus its inline padding. */
export const estimateText = (el: HTMLElement): number =>
  Math.max(px(el.style.minWidth) ?? 0, textWidth(ownText(el), textStyleOf(el), horizontalPadding(el)));

/** The widest line an element holds: its own text, or a child on a line of its own (each at its own style), plus the element's inline padding. */
export function estimateWidest(el: HTMLElement): number {
  let widest = estimateText(el);
  const pad = horizontalPadding(el);
  for (const c of el.children) if (ownLine(c as HTMLElement)) widest = Math.max(widest, estimateWidest(c as HTMLElement) + pad);
  return widest;
}

/**
 * A header cell in a table laid out `auto` (the Table block's measuring pass,
 * `width: max-content`) is as wide as its column: the widest of the header
 * and every cell under it — a cell's widest line, so a value block or a
 * folded row counts — as the browser would size it. Pinned (`fixed`)
 * layout measures the header's own text like any cell.
 */
export const columnWidth = (th: HTMLElement): number => {
  const table = th.closest<HTMLElement>('table');
  const row = th.parentElement;
  if (!table || !row || table.style.tableLayout === 'fixed') return estimateText(th);
  const index = [...row.children].indexOf(th);
  let width = estimateText(th);
  for (const tr of table.querySelectorAll<HTMLElement>('tbody tr')) {
    const td = tr.children[index] as HTMLElement | undefined;
    if (td && td.style.display !== 'none') width = Math.max(width, estimateWidest(td));
  }
  return width;
};

/** The estimating measurer, with the box measure exposed for checkers that need the box a text sits in. */
export type Estimator = Measurer & { box: (el: HTMLElement) => number };

export function estimator(frame: number): Estimator {
  const boxWidth = (el: HTMLElement): number => {
    if (el === document.documentElement || el === document.body || !el.parentElement) return frame;
    const own = px(el.style.width) ?? px(el.style.maxWidth);
    const parent = el.parentElement;
    let base = boxWidth(parent) - horizontalPadding(parent);
    // A grid parent shares its width between its columns.
    const grid = /repeat\((\d+)/.exec(parent.style.gridTemplateColumns ?? '');
    if (grid) { const n = Number(grid[1]); const gap = px(parent.style.gap) ?? 0; base = (base - gap * (n - 1)) / n; }
    // A sidebar beside the content takes its width off the content.
    if (parent.tagName === 'NISLI-APP') {
      const nav = parent.querySelector<HTMLElement>(':scope > div > nav');
      if (nav && nav.style.display !== 'none') base -= px(nav.style.width) ?? metrics.layout.sidebarWidth;
    }
    if (el.style.display === 'contents') return base;
    return own !== undefined ? Math.min(own, base) : base;
  };

  const measure: Estimator = (el) => (el.tagName === 'TH' ? columnWidth(el) : isTextual(el) ? estimateText(el) : boxWidth(el));
  measure.box = boxWidth;
  return measure;
}
